version: "0.1"
user: prateek.delguy
key: 9DjIGDAUAnyqaNELLFGeGyLCcdW2W4diRXje0U5yaHr8nAReqE
testSuites: []
pre: [echo "Test"]
runson: win
autosplit: true
concurrency: 2
testDiscovery:
  autosubset: true
  command: grep -lr 'testSuiteGuid' */*.ts | sed 's/...$//g'
  mode: dynamic
  type: raw
testRunnerCommand: katalonc `-noSplash `-runMode=console `-projectPath="$Env:HYPEREXECUTE_WORKING_DIR\Hyperexecute_Sample.prj"
  `-retry=0 `-testSuitePath="$test" `-browserType="firefox" `-executionProfile="default"
  `-apiKey="" `-`-config `-webui.autoUpdateDrivers=true
globalTimeout: 90
tunnelOpts:
  global: true
testSuiteTimeout: 90
testSuiteStep: 90
maxRetries: 1
jobID: 9b620f64-9c61-49ae-8f98-1bce00dd26dd
codeDirectory: Hyperexecute-Katalon-sample
framework:
  name: ""
  flags: []
  discoveryFlags: []
  discoveryType: ""
  runnerFlags: []
  workingDirectory: ""
  isTestNGXMLSuite: false
  defaultReports: true
cypress: false
betaFeature:
  setPartiallyCompletedAsCompleted: false
combineTasksInMatrixMode: false
